[project]
name = "justjustwatch"
version = "0.1.0"
description = "CLI tool to search movies and shows availability on JustWatch"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inquirerpy>=0.3.4",
    "requests>=2.34.2",
    "tabulate>=0.9.0",
    "tqdm>=4.68.3",
]

[dependency-groups]
dev = [
    "pylint>=3.3.9",
]